### ISSUE TITLE
Read: Memory Leak on (zlib) Compressed Files

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#67]
The python API's `read()` (or `[]`) operation leaks a lot of memory.

In my case, I am opening a large set of 1D variables, each with dimensionality `(5e9,)` , and read them chunk-wise (because in that way I am using the aggregation and striding on OSTs in an optimal way since I still know how the chunks were distributed from a lookup table I created. it also limits the underlying posix open/close calls to the aggregated files in `*.bp.dir/` to a minimum):
```python
        for patch in patchList :
            # skip empty patches
            if patch.numParticles == 0 :
                continue

            n = patch.numParticlesOffset
            nEnd = patch.numParticles + patch.numParticlesOffset

            for r in particle_records :
                fa.var[r].read((n,), (nEnd-n,))
```

in this case, the inner loop just eats up memory, visible in (h)top and [memory_profiler](http://deeplearning.net/software/theano/tutorial/python-memory-management.html#internal-memory-management) and finally leading to swapping (although I never copy chunks larger then a few GB at a time).

~~I found a way to reduce the leak a bit by closing and opening the file sporadically~~ *update: no that is not working, it's just slower...*
```python
            #[...]
            for r in particle_records :
                fa.var[r].read((n,), (nEnd-n,))

            # fix some memory leaks in adios `read()`
            if patch_number % 4 == 0 :
                fa.close()
                fa = ad.file( bpfile_name )

            gc.collect()
```

~~but even in this case the `close()` call does not free all memory allocated in the `file()` open step. Nevertheless, trading the the `open/close` leak (several 100 MB per 1k open/closes, maybe related to #58) against the `read()` leak (several dozen GBs) is still not ideal ;)~~

Any idea what could be wrong here?

I am computing on Rhea (ORNL) with ADIOS 1.9.0

**Comment by ax3l** [comment]
note: the data I read is compressed.

**Comment by yyalli** [comment]
I have something to do in this week but I should be able to look at this problem in the next week. Honestly, I didn't pay attention on the memory consumption in the python wrapper. It will be a good opportunity to look into.

By the way, how the data is compressed? Did you use the compression method in Adios?

--
Jong Youl Choi
Scientific Data Group
Computer Science and Math Division
Oak Ridge National Laboratory
Homepage: http://www.ornl.gov/~jyc/

On May 12, 2016, at 12:19 PM, Axel Huebl <notifications@github.com<mailto:notifications@github.com>> wrote:


note: the data I read is compressed.

**Comment by ax3l** [comment]
I am using `szip` compression on the aggregated files.

Digged a bit deeper and the problem is not with python but with *general reads of transformed/compressed data sets*. (btw: exposing the transform to the python layer to allow writing compressed data sets for tests would be awesome :) [here is how h5py does it](http://docs.h5py.org/en/latest/high/dataset.html#filter-pipeline), we could e.g. just add it to the `define_var` API).

Here is a minimal example to reproduce the problem in python:

```python
#!/usr/bin/env python
#
import adios as ad

import memory_profiler

@profile
def readLoop(f):
    i = 0
    while i < 1e4 :
        f.var["xy"].read()
        i += 1

#f = ad.file("data_uncompressed.bp")
f = ad.file("data_compressed.bp")

#print(f.var.keys())
readLoop(f)

f.close()
```

Results running `python -m memory_profiler ./readTestLeak.py` on **compressed data set**:
```
Filename: ./readTestLeak.py

Line #    Mem usage    Increment   Line Contents
================================================
     7   32.953 MiB    0.000 MiB   @profile
     8                             def readLoop(f):
     9   32.957 MiB    0.004 MiB       i = 0
    10   41.664 MiB    8.707 MiB       while i < 1e4 :
    11   41.664 MiB    0.000 MiB           f.var["xy"].read()
    12   41.664 MiB    0.000 MiB           i += 1
```

and on the **uncompressed data set**:
```
Filename: ./readTestLeak.py

Line #    Mem usage    Increment   Line Contents
================================================
     7   32.668 MiB    0.000 MiB   @profile
     8                             def readLoop(f):
     9   32.672 MiB    0.004 MiB       i = 0
    10   33.559 MiB    0.887 MiB       while i < 1e4 :
    11   33.559 MiB    0.000 MiB           f.var["xy"].read()
    12   33.559 MiB    0.000 MiB           i += 1
```

see the change in `line 10` which is the closest report one can get around this . Alternatively, one can also follow `top` to see the leak accumulating on the compressed reads.

Here are the `.bp` files I used (created by hacking the `performance` test):
[data_uncompressed.tar.gz](https://github.com/ornladios/ADIOS/files/262820/data_uncompressed.tar.gz)
[data_compressed.tar.gz](https://github.com/ornladios/ADIOS/files/262819/data_compressed.tar.gz)

**Comment by ax3l** [comment]
corrected a typo: using `zlib` on my files.

**Comment by ax3l** [comment]
@pnorbert Here is also a low-level C example which shows the same memory leak in the loop of `schedule` and `perform` read on compressed (zlib) files ([attached online](https://github.com/ornladios/ADIOS/files/262869/readLeak.c.txt)).

```bash
ARD=$HOME/lib/adios-1.9.0
mpiCC readLeak.c -L$ARD/lib -I$ARD/include -o readLeak.o -ladios -lz
```
[readLeak.c.txt](https://github.com/ornladios/ADIOS/files/262869/readLeak.c.txt)

**Comment by ax3l** [comment]
(valgrind results) It's a bit hard to debug but it looks like quite a few functions leak memory on the way. I am just listing the larger ones:

- `adios_read_open`: 192 bytes in 4 blocks + 2x8 bytes in 1 blocks + 36 bytes in 4 blocks (`adios_transform_deserialize_transform_characteristic`) + 192 bytes in 4 blocks (`adios_transform_deserialize_transform_characteristic`)
- `adios_schedule_read`: 16 bytes in 1 blocks + 16 bytes in 1 blocks + 2x64 bytes in 4 blocks (`adios_selection_intersect_bb_bb`) + 160 bytes in 4 blocks (`common_read_selection_writeblock`)
- `adios_perform_reads`: 32 bytes in 4 blocks (`read_var_wb`) + 2x64 bytes in 4 blocks (`adios_selection_intersect_bb_bb`)
- ...
- `check_bp_validity`: 64 bytes in 1 blocks
- `adios_read_init_method`: 21 bytes in 1 blocks + 31 bytes in 1 blocks (2x `adios_read_hooks_init`) + 96 bytes in 1 blocks (`adios_query_hooks_init`) + 1,512 bytes in 1 blocks (`adios_read_hooks_init`)
- `open_stream`: 5 bytes in 1 blocks + 8 bytes in 1 blocks + 16 bytes in 1 blocks
- `bp_open`: 48 bytes in 1 blocks (`bp_read_open`) + 56 bytes in 1 blocks


[valgrind.txt](https://github.com/ornladios/ADIOS/files/262905/valgrind.txt)

**Comment by ax3l** [comment]
Looks like the programmer of transforms did not know the *deep delete call* for `selections` aka `free_selection` and just used `common_read_selection_delete()` at all places (even when having ownership over the selection object).

After a day of debugging, @psychocoderHPC and me found the following leaks in selections that seem to be called that often that they can cause severe memory leaks on transformed, aggregated files (as reported above):

```patch
diff --git a/src/core/transforms/adios_patchdata.c b/src/core/transforms/adios_patchdata.c
index 8137c8b..49f0626 100644
--- a/src/core/transforms/adios_patchdata.c
+++ b/src/core/transforms/adios_patchdata.c
@@ -85,7 +85,7 @@ inline static uint64_t adios_patch_data_bb_to_bb(void *dst, uint64_t dst_ragged_
     // Cleanup
     free(inter_off_relative_to_dst);
     free(inter_off_relative_to_src);
-    common_read_selection_delete(inter_sel);
+    free_selection(inter_sel);
 
     return volume;
 }
diff --git a/src/core/transforms/adios_transforms_read.c b/src/core/transforms/adios_transforms_read.c
index 6e564fd..bbeaf3d 100644
--- a/src/core/transforms/adios_transforms_read.c
+++ b/src/core/transforms/adios_transforms_read.c
@@ -217,6 +217,8 @@ static int generate_read_request_for_pg(
        abort(); // Should never be called with other types of selections
     }
 
+    free_selection( pg_writeblock_sel );
+
     // If there is an intersection, generate a corresponding PG read request
     if (pg_intersection_sel) {
         // Make a PG read request group, and fill it with some subrequests, and link it into the read reqgroup
@@ -584,8 +586,7 @@ static uint64_t apply_datablock_to_buffer_and_free(
                if (out_inter_sel) {
                        *out_inter_sel = inter_sel;
                } else {
-                       // TODO: Deep delete the selection (delete points list, start/count arrays, etc.)
-                       common_read_selection_delete(inter_sel);
+                       free_selection(inter_sel);
                }
        }
 
@@ -766,6 +767,7 @@ static ADIOS_VARCHUNK * extract_chunk_from_finished_read_reqgroup(adios_transfor
 
     // Transfer ownership of orig_sel
     chunk->sel = copy_selection(reqgroup->orig_sel);
+    // TODO: why is orig_sel not free'd?
     reqgroup->orig_sel = NULL;
 
     return chunk;
diff --git a/src/core/transforms/adios_transforms_reqgroup.c b/src/core/transforms/adios_transforms_reqgroup.c
index b3e82ab..2f4de17 100644
--- a/src/core/transforms/adios_transforms_reqgroup.c
+++ b/src/core/transforms/adios_transforms_reqgroup.c
@@ -42,7 +42,7 @@
 // An adios_transform_raw_read_request corresponds to a single raw byte range read within a PG
 
 // adios_transform_raw_read_request owns ->sel and ->data (both will be free'd)
-// adios_transform_pg_read_request owns ->pg_selection and ->pg_intersection_to_global_copyspec (both will be free'd)
+// adios_transform_pg_read_request owns ->pg_intersection_sel and ->pg_intersection_to_global_copyspec (both will be free'd)
 // adios_transform_read_request owns ->orig_sel, ->varinfo and ->transinfo (all will be free'd)
 
 // Also, in all cases, ->transform_internal will be free'd if it is non-NULL
@@ -236,7 +236,7 @@ void adios_transform_raw_read_request_free(adios_transform_raw_read_request **su
     assert(!subreq->next); // Not a perfect check, but will catch many requests that are still linked
 
     // Free malloc'd resources
-    common_read_selection_delete(subreq->raw_sel);
+    free_selection(subreq->raw_sel);
     MYFREE(subreq->data);
     MYFREE(subreq->transform_internal);
 
@@ -323,7 +323,7 @@ void adios_transform_pg_read_request_free(adios_transform_pg_read_request **pg_r
 
     // Free malloc'd resources
     if (pg_reqgroup->pg_intersection_sel)
-        common_read_selection_delete((ADIOS_SELECTION*)pg_reqgroup->pg_intersection_sel);
+        free_selection((ADIOS_SELECTION*)pg_reqgroup->pg_intersection_sel);
     if (pg_reqgroup->pg_bounds_sel)
         common_read_selection_delete((ADIOS_SELECTION*)pg_reqgroup->pg_bounds_sel);
     if (pg_reqgroup->pg_writeblock_sel)
@@ -431,7 +431,8 @@ void adios_transform_read_request_free(adios_transform_read_request **reqgroup_p
     if (reqgroup->lent_varchunk_data)
         MYFREE(reqgroup->lent_varchunk_data);
 
-    common_read_selection_delete((ADIOS_SELECTION*)reqgroup->orig_sel); // Remove const
+    free_selection((ADIOS_SELECTION*)reqgroup->orig_sel); // Remove const
+    reqgroup->orig_sel = NULL;
 
     // DON'T FREE varinfo/transinfo, since they are stored in the infocache
     // common_read_free_transinfo(reqgroup->raw_varinfo, (ADIOS_TRANSINFO*)reqgroup->transinfo); // Remove const
```

We will open a pull request. Seems to work for our problem in the C++ example but a detailed review would be great! :)

**Comment by pnorbert** [comment]
We are revising the selections in the minmax branch, and the bounding box
selections are now always copied (they were pointing to user data before).
Therefore, the coming common_read_selection_delete() should fix the memory
leaks. We plan to remove the free_selection() now that it is redundant.
Can you give a try to your tests with the minmax branch?

void common_read_selection_delete (ADIOS_SELECTION *sel)
{
    if (sel->type == ADIOS_SELECTION_POINTS &&
sel->u.points.container_selection != NULL)
    {
       common_read_selection_delete (sel->u.points.container_selection);
    }
    else if (sel->type == ADIOS_SELECTION_BOUNDINGBOX)
    {
        if (sel->u.bb.start) {
            free (sel->u.bb.start);
            sel->u.bb.start = NULL;
        }
        if (sel->u.bb.count) {
            free (sel->u.bb.count);
            sel->u.bb.count = NULL;
        }
    }
    free(sel);
}

**Comment by ax3l** [comment]
No, there are still leaks in the `minmax` branch as severe as before with my tests.

Here is my valgrind log from `minmax`: [valgrind.txt](https://github.com/ornladios/ADIOS/files/263493/valgrind.txt)

**Comment by ax3l** [comment]
Still a :+1: that you are refactoring the selections.

**Comment by ax3l** [comment]
One thing that is still missing in `minmax` is as in the patch above the free at `generate_read_request_for_pg`:
```patch
diff --git a/src/core/transforms/adios_transforms_read.c b/src/core/transforms/adios_transforms_read.c
index 6e564fd..c513101 100644
--- a/src/core/transforms/adios_transforms_read.c
+++ b/src/core/transforms/adios_transforms_read.c
@@ -217,6 +217,8 @@ static int generate_read_request_for_pg(
        abort(); // Should never be called with other types of selections
     }
 
+    free_selection( pg_writeblock_sel );
+
     // If there is an intersection, generate a corresponding PG read request
     if (pg_intersection_sel) {
         // Make a PG read request group, and fill it with some subrequests, and link it into the read reqgroup
```

but there are new memory leaks in this branch that still have some selections to clean up: [valgrind.txt](https://github.com/ornladios/ADIOS/files/263593/valgrind.txt)

**Comment by pnorbert** [comment]
I have committed fixes for the leaks in the minmax branch. Let me know if
you still have other leaks.

**Comment by ax3l** [comment]
@pnorbert thank you for the updates on the `minmax` branch. I checked with the latest updates that went in 12hrs ago as of 27b0cf9921265945ccbaa2bb113f07cfb4e7fde5 and for the tests I did it looks leak-free, yeah-a! Thank you! :sparkles: 

For my progress on the post-processing I do on Rhea: Do you know then the `minmax` branch will be merged to `master`? I am working on a `1.9.0` state of ADIOS and though about just doing a minimal patch as described above to keep the library on a stable (conservative) state since I am working on production data. Do you think the patch I provided [here (above)](https://github.com/ornladios/ADIOS/issues/67#issuecomment-219038203) is correct or what would you recommend?

Thank you!

**Comment by pnorbert** [comment]
Your fixes are fine for 1.9.0 but I did it differently in the minmax
branch. I still need to test the minmax branch for queries before I merge
it back to master. A few weeks.

**Comment by ax3l** [comment]
sounds great. thank you very much for the review and the upcoming changes! :fireworks:

**Comment by ax3l** [comment]
`minmax` is now merged into `master` as of a3acf7949b7328c22df561ae9cfd51bd71169e57.
